version: "2"

services:
  app:
    build: .
    environment:
      REDIS_ADDR: redis://redis:6379
    links:
      - redis
    depends_on:
      - redis
    env_file: .env
  redis:
    image: redis
    ports:
      - 6379
